ports:
  - port: 3000
    visibility: public
    onOpen: open-browser

tasks:
  - name: Terminal 1
    before: echo 'run once codes'
    init: npm install && echo '\n\n done `npm install` \n\n'
    command: npm build
